- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install packages
      include: install-packages.yml
- hosts: localhost
  become: no
  tasks:
    - name: Setup git
      include: setup-git.yml
    - name: Clone assets repository
      git:
        repo: "git@gitlab.com:kaineer/kaineer.git"
        dest: "~/git/kaineer"
        recursive: yes
