- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install packages
      include: install-packages.yml
- hosts: localhost
  become: no
  tasks:
    - name: Setup git
      include: packages/git.yml
    - name: Setup neovim
      include: packages/nvim.yml
    - name: Setup tmux
      include: packages/tmux.yml
    - name: Setup node
      include: packages/node.yml
