- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install packages
      include: install-packages.yml
- hosts: localhost
  become: no
  tasks:
    - name: Setup git
      include: setup-git.yml
    - include: config-repositories.yml
